labels:
  - name: patch
    color: '207de5'
  - name: minor
    color: '009800'
  - name: major
    color: 'e11d21'
  - name: bug
    color: 'fc2929'
  - name: critical
    color: 'fc2929'
  - name: vendor
    color: 'ededed'
  - name: pending author
    color: 'ededed'
  - name: in progress
    color: 'ededed'
  - name: RTM
    color: 'ffffff'
  - name: docs
    color: 'fbca04'
  - name: review required
    color: 'd4c5f9'
  - name: help wanted
    color: '0e8a16'
  - name: Needs: Documentation
    color: '006b75'
  - name: Needs: Tests
    color: '006b75'
  - name: Needs: Changelog note
    color: '006b75'

projects:
  admin-bundle: ~
  admin-search-bundle: ~
  block-bundle: ~
  cache: ~
  cache-bundle: ~
  classification-bundle: ~
  comment-bundle: ~
  core-bundle: ~
  dashboard-bundle: ~
  datagrid-bundle: ~
  doctrine-extensions: ~
  doctrine-mongodb-admin-bundle: ~
  doctrine-orm-admin-bundle: ~
  doctrine-phpcr-admin-bundle: ~
  easy-extends-bundle: ~
  ecommerce: ~
  exporter:
    branches:
      master:
        php_versions: ['5.3', '5.4', '5.5', '5.6', '7.0']
        symfony_versions: ['2.3', '2.6', '2.7', '2.8', '3.0']
        docs_path: docs
  formatter-bundle: ~
  google-authenticator: ~
  intl-bundle: ~
  media-bundle: ~
  news-bundle: ~
  notification-bundle: ~
  page-bundle: ~
  propel-admin-bundle: ~
  sandbox: ~
  seo-bundle: ~
  sonata-composer: ~
  timeline-bundle: ~
  translation-bundle: ~
  user-bundle: ~
