labels:
  - name: patch
    color: '207de5'
  - name: minor
    color: '009800'
  - name: major
    color: 'e11d21'
  - name: bug
    color: 'fc2929'
  - name: vendor
    color: 'ededed'
  - name: pending author
    color: 'dddddd'
  - name: RTM
    color: 'ffffff'

projects:
  cache: ~
  exporter: ~
  admin-bundle: ~
