name: app

type: php:7.4

runtime:
    extensions:
        - mbstring
        - sodium
        - ctype
        - iconv
        - json

relationships:
    redis: "github:redis"

variables:
    php-ext:
        - "redis:5.3.1"

build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 512

mounts:
    "/var": {source: local, source_path: var}

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

crons:
    comment-non-mergeable-pull-requests:
        spec: '*/10 * * * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape bin/console comment-non-mergeable-pull-requests --apply
            fi
    pull-request-auto-merge:
        spec: '*/5 * * * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape bin/console pull-request-auto-merge --apply
            fi
    auto-merge:
        spec: '0 2 * * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape bin/console auto-merge --apply
            fi
    dispatch-labels:
        spec: '0 */4 * * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape bin/console dispatch:labels --apply
            fi
    dispatch-webhooks:
        spec: '0 */6 * * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape bin/console dispatch:hooks --apply
            fi
    dispatch-settings:
        spec: '0 5 * * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape bin/console dispatch:settings --apply
            fi
    dispatch-topics:
        spec: '0 5 * * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape bin/console dispatch:topics --apply
            fi
    dispatch-files:
        spec: '5 */4 * * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape bin/console dispatch:files --apply
            fi
    dispatch-branches-protection:
        spec: '10 */4 * * *'
        cmd: |
            if [ "$SYMFONY_BRANCH" = master ]; then
                croncape bin/console dispatch:branches-protection --apply
            fi
