monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        grouped:
            type: group
            members: [nested, slack_errors]
        nested:
            type: stream
            path: php://stderr
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        slack_errors:
            type: slack
            token: '%env(SLACK_TOKEN)%'
            channel: 'dev-kit-logs'
            bot_name: '@@dev-kit-logger'
            level: debug
            include_extra: true
        slack:
            type: slack
            token: '%env(SLACK_TOKEN)%'
            channel: 'ci'
            bot_name: '@@dev-kit-logger'
            level: debug
            include_extra: true
            use_short_attachment: true
            channels: ['automerge']
